### ISSUE TITLE
Unable to decrypt clear key encrypted content

### ISSUE THREAD

**Issue by HimanshuSaikia** [davidjamesherzog/videojs-shaka#16]
I am using bento4 mp4encrypt to encrypt using clear key:

``mp4encrypt --method MPEG-CENC --key 1:70858D20A19F58A740C58180E699B4AA:random --property 1:KID:A16E402B9401E372F36D064AA62BB749 --key 2:70858D20A19F58A740C58180E699B4AA:random --property 2:KID:A16E402B9401E372F36D064AA62BB749 --global-option mpeg-cenc.eme-pssh:true "${file%.*}/${file%.*}_720p_frag".mp4 "${file%.*}/${file%.*}_720p_encrypted".mp4``

In the above command we are using the same key and keyID to encrypt both the video and the audio 

And using this in the js

```js
var url='T04_Sourcing of Accounting Systems/stream.mpd';
var options = {
	src: url,
	type: 'application/dash+xml',
}; 
var player = videojs('video', {
	autoplay: true,
	width: 800,
	height: 450,
	techOrder: ['shaka'],
	shaka: {
	    debug: true,
            drm: {
	    clearKeys: {
		'A16E402B9401E372F36D064AA62BB749': '70858D20A19F58A740C58180E699B4AA',
                'A16E402B9401E372F36D064AA62BB749': '70858D20A19F58A740C58180E699B4AA'
	    }
	},
}
});
player.qualityPickerPlugin();
player.src(options);
```

The unencrypted dash content is playing but the encrypted content keeps buffering with no errors in the console. Also, encrypted content is playing in videojs without shaka tech and dashjs player.
Please bro, help me out in this.

**Comment by davidjamesherzog** [comment]
@HimanshuSaikia - Unfortunately, I haven't had any experience with clearKeys before.  Can we trying the following?

1) Have you tried this video with the shaka player demo - https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=HOME;build=uncompiled ?  If so, did you get it working?  If not, please try and get this working with the stand alone shaka player first.  `videojs-shaka` is just a plugin that bridges the gap between video.js and shaka player.  You need to get this working with shaka first.
2) If you have already succeeded with number one, can you provide an example for me to test with ? If I have an example that works with shaka player, then I might be able to figure out what the problem is.

Thanks

**Comment by HimanshuSaikia** [comment]
> 
> 
> @HimanshuSaikia - Unfortunately, I haven't had any experience with clearKeys before. Can we try the following?
> 
>     1. Have you tried this video with the shaka player demo - https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=HOME;build=uncompiled ?  If so, did you get it working?  If not, please try and get this working with the stand alone shaka player first.  `videojs-shaka` is just a plugin that bridges the gap between video.js and shaka player.  You need to get this working with shaka first.
> 
>     2. If you have already succeeded with number one, can you provide an example for me to test with ? If I have an example that works with shaka player, then I might be able to figure out what the problem is.
> 
> 
> Thanks

Thanks for your response bro. But, I debugged it myself and it's up and running now. After analysing the generated mpd file from Bento4, I found out that it wasn't adding the cenc key to the mpd file.
``
Previously I did in two steps - 
1) Encrypt the file using mp4encrypt 2) Dash it using mp4-dash. So, it seems, shaka doesn't recognise this format as cenc keys aren't present in the mpd.
So, what I did is without using mp4encrypt, I directly used mp4-dash on the fragmented file but used the following options --encryption-key=KEYID:KEY --encryption-cenc-scheme=cenc with mp4-dash and it worked fine in both shaka and video-js-shaka. This is probably unreported and unseen by Bento4.
Thanks for the wonderful library. You are awesome. Stay Safe.
``

**Comment by davidjamesherzog** [comment]
@HimanshuSaikia - Glad you figured out the issue.  I hope this library helps you.
