### ISSUE TITLE
Ability to pass configuration to shaka

### ISSUE THREAD

**Issue by krychu90** [davidjamesherzog/videojs-shaka#34]
Hello,
there is no ability to pass configuration to shaka-player except drm.
Can you improve your plugin that will be possible to pass other configuration to { shaka: {} } property?

Regards

**Comment by davidjamesherzog** [comment]
So, sounds like you want to be able to pass any of these values and not just the `drm` one that it currently supports?

**Comment by krychu90** [comment]
> So, sounds like you want to be able to pass any of these values and not just the `drm` one that it currently supports?
> 
> https://shaka-player-demo.appspot.com/docs/api/tutorial-config.html

Yes
