### ISSUE TITLE
Shaka "buffering" event map to MediaElement event "waiting" 

### ISSUE THREAD

**Issue by jzhoubupt** [davidjamesherzog/videojs-shaka#40]
**Have you checked for duplicate open issues [here](https://github.com/davidjamesherzog/videojs-shaka/issues)?**
Yes

**What version of Shaka Player and videojs-shaka are you using?**
Shaka 3.0.9 with latest videojs-shaka

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `master`?**
Yes

**Are you using the demo app or your own custom app?**
any app

**If custom app, can you reproduce the issue using our demo app?**

**What browser and OS are you using?**
Chrome and any others

**What are the manifest and license server URIs?**
clear stream

**What did you do?**

listen to video-js event "buffering" and "playing" when play a DASH stream

**What did you expect to happen?**
When player comes to buffering, it fire "waiting" event;
When player resume from buffering, it fire "playing" event

**What actually happened?**
No "playing" event

The root cause of the issue is on following code in shaka.js:
this.shaka_.addEventListener('buffering', function(event) {
      if (event.buffering) me.vjsPlayer.trigger('waiting');
    });

Shaka player fire "buffering" event with true/false to indicate buffering/leave-buffering state: https://shaka-player-demo.appspot.com/docs/api/shaka.Player.html#.event:BufferingEvent
While the above code didn't respect that value.

**Comment by davidjamesherzog** [comment]
@jzhoubupt - Thanks for finding the issue.  I will take a look.

**Comment by davidjamesherzog** [comment]
@jzhoubupt - Please check out the above pull request.

**Comment by jzhoubupt** [comment]
Thanks David and we are aligned on the change!

**Comment by davidjamesherzog** [comment]
@jzhoubupt - Version 1.1.1 has been published - https://www.npmjs.com/package/videojs-shaka
